# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customListForAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_customListForAdmin(object):
    def setupUi(self, MainWindow_customListForAdmin):
        MainWindow_customListForAdmin.setObjectName("MainWindow_customListForAdmin")
        MainWindow_customListForAdmin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_customListForAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget_customTable = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_customTable.setObjectName("tableWidget_customTable")
        self.tableWidget_customTable.setColumnCount(0)
        self.tableWidget_customTable.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_customTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_showCustom = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_showCustom.setFont(font)
        self.pushButton_showCustom.setObjectName("pushButton_showCustom")
        self.horizontalLayout.addWidget(self.pushButton_showCustom)
        self.pushButton_deleteCustom = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_deleteCustom.setFont(font)
        self.pushButton_deleteCustom.setObjectName("pushButton_deleteCustom")
        self.horizontalLayout.addWidget(self.pushButton_deleteCustom)
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow_customListForAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_customListForAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow_customListForAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_customListForAdmin)
        self.statusbar.setObjectName("statusbar")
        MainWindow_customListForAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_customListForAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_customListForAdmin)

    def retranslateUi(self, MainWindow_customListForAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_customListForAdmin.setWindowTitle(_translate("MainWindow_customListForAdmin", "顾客信息管理"))
        self.label.setText(_translate("MainWindow_customListForAdmin", "顾客信息管理"))
        self.pushButton_showCustom.setText(_translate("MainWindow_customListForAdmin", "查询顾客信息"))
        self.pushButton_deleteCustom.setText(_translate("MainWindow_customListForAdmin", "删除顾客信息"))
        self.pushButton_quit.setText(_translate("MainWindow_customListForAdmin", "退出"))
