# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteCustom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_deleteCustom(object):
    def setupUi(self, Dialog_deleteCustom):
        Dialog_deleteCustom.setObjectName("Dialog_deleteCustom")
        Dialog_deleteCustom.resize(787, 176)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_deleteCustom)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_deleteCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget_deleteRow = QtWidgets.QTableWidget(Dialog_deleteCustom)
        self.tableWidget_deleteRow.setObjectName("tableWidget_deleteRow")
        self.tableWidget_deleteRow.setColumnCount(0)
        self.tableWidget_deleteRow.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_deleteRow)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_sureDelete = QtWidgets.QPushButton(Dialog_deleteCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sureDelete.setFont(font)
        self.pushButton_sureDelete.setObjectName("pushButton_sureDelete")
        self.horizontalLayout.addWidget(self.pushButton_sureDelete)
        self.pushButton_quit = QtWidgets.QPushButton(Dialog_deleteCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_deleteCustom)
        QtCore.QMetaObject.connectSlotsByName(Dialog_deleteCustom)

    def retranslateUi(self, Dialog_deleteCustom):
        _translate = QtCore.QCoreApplication.translate
        Dialog_deleteCustom.setWindowTitle(_translate("Dialog_deleteCustom", "删除顾客信息"))
        self.label.setText(_translate("Dialog_deleteCustom", "删除顾客信息"))
        self.pushButton_sureDelete.setText(_translate("Dialog_deleteCustom", "确定删除"))
        self.pushButton_quit.setText(_translate("Dialog_deleteCustom", "取消"))
