# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageForAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_manageForAdmin(object):
    def setupUi(self, MainWindow_manageForAdmin):
        MainWindow_manageForAdmin.setObjectName("MainWindow_manageForAdmin")
        MainWindow_manageForAdmin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_manageForAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_customManage = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_customManage.setFont(font)
        self.pushButton_customManage.setObjectName("pushButton_customManage")
        self.horizontalLayout.addWidget(self.pushButton_customManage)
        self.pushButton_menuManage = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_menuManage.setFont(font)
        self.pushButton_menuManage.setObjectName("pushButton_menuManage")
        self.horizontalLayout.addWidget(self.pushButton_menuManage)
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow_manageForAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_manageForAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow_manageForAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_manageForAdmin)
        self.statusbar.setObjectName("statusbar")
        MainWindow_manageForAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_manageForAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_manageForAdmin)

    def retranslateUi(self, MainWindow_manageForAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_manageForAdmin.setWindowTitle(_translate("MainWindow_manageForAdmin", "菜单系统管理"))
        self.label.setText(_translate("MainWindow_manageForAdmin", "菜单系统管理"))
        self.pushButton_customManage.setText(_translate("MainWindow_manageForAdmin", "顾客管理"))
        self.pushButton_menuManage.setText(_translate("MainWindow_manageForAdmin", "菜单管理"))
        self.pushButton_quit.setText(_translate("MainWindow_manageForAdmin", "取消"))
