# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectCustom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_selectCustom(object):
    def setupUi(self, Dialog_selectCustom):
        Dialog_selectCustom.setObjectName("Dialog_selectCustom")
        Dialog_selectCustom.resize(650, 484)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_selectCustom)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_phonenumber = QtWidgets.QCheckBox(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_phonenumber.setFont(font)
        self.checkBox_phonenumber.setObjectName("checkBox_phonenumber")
        self.horizontalLayout.addWidget(self.checkBox_phonenumber)
        self.lineEdit_phonenumber = QtWidgets.QLineEdit(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_phonenumber.setFont(font)
        self.lineEdit_phonenumber.setObjectName("lineEdit_phonenumber")
        self.horizontalLayout.addWidget(self.lineEdit_phonenumber)
        self.pushButton_selectCustom = QtWidgets.QPushButton(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_selectCustom.setFont(font)
        self.pushButton_selectCustom.setObjectName("pushButton_selectCustom")
        self.horizontalLayout.addWidget(self.pushButton_selectCustom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_customName = QtWidgets.QCheckBox(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_customName.setFont(font)
        self.checkBox_customName.setObjectName("checkBox_customName")
        self.horizontalLayout_2.addWidget(self.checkBox_customName)
        self.lineEdit_customName = QtWidgets.QLineEdit(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_customName.setFont(font)
        self.lineEdit_customName.setObjectName("lineEdit_customName")
        self.horizontalLayout_2.addWidget(self.lineEdit_customName)
        self.pushButton_quit = QtWidgets.QPushButton(Dialog_selectCustom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_2.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget_customList = QtWidgets.QTableWidget(Dialog_selectCustom)
        self.tableWidget_customList.setObjectName("tableWidget_customList")
        self.tableWidget_customList.setColumnCount(0)
        self.tableWidget_customList.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_customList)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_selectCustom)
        QtCore.QMetaObject.connectSlotsByName(Dialog_selectCustom)

    def retranslateUi(self, Dialog_selectCustom):
        _translate = QtCore.QCoreApplication.translate
        Dialog_selectCustom.setWindowTitle(_translate("Dialog_selectCustom", "顾客信息查询"))
        self.label.setText(_translate("Dialog_selectCustom", "顾客信息查询"))
        self.checkBox_phonenumber.setText(_translate("Dialog_selectCustom", "手机号码"))
        self.pushButton_selectCustom.setText(_translate("Dialog_selectCustom", "查询"))
        self.checkBox_customName.setText(_translate("Dialog_selectCustom", "用户名称"))
        self.pushButton_quit.setText(_translate("Dialog_selectCustom", "取消"))
